[font]

normal.family      = 'Hack Nerd Font Mono'
bold.family        = 'Hack Nerd Font Mono'
italic.family      = 'Hack Nerd Font Mono'
bold_italic.family = 'Hack Nerd Font Mono'

size = 14

# Everforest Dark Hard
[colors.primary]
background = '#272e33'
foreground = '#d3c6aa'

[colors.normal]
black   = '#414b50'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

[colors.bright]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

[keyboard]

bindings = [
  { key = 'N',        mods = 'Control|Shift', action = 'SpawnNewInstance'  },
  { key = 'PageUp',   mods = 'Control'      , action = 'SelectPreviousTab' },
  { key = 'PageDown', mods = 'Control'      , action = 'SelectNextTab'     },
]
