[font]

normal.family      = 'Hack Nerd Font Mono'
bold.family        = 'Hack Nerd Font Mono'
italic.family      = 'Hack Nerd Font Mono'
bold_italic.family = 'Hack Nerd Font Mono'

size = 14

[colors.primary]

background = '#282c34'
foreground = '#abb2bf'

[colors.normal]

black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

[colors.bright]

black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

[keyboard]

bindings = [
  { key = 'N',        mods = 'Control|Shift', action = 'SpawnNewInstance'  },
  { key = 'PageUp',   mods = 'Control'      , action = 'SelectPreviousTab' },
  { key = 'PageDown', mods = 'Control'      , action = 'SelectNextTab'     },
]
